function h = menu_callback_show_abaut_figure(~,~)

mainFigObj=findall(0,'Type','figure','Tag','mainFigure');

% ------------------ Main Figure Fallback ------------------
if isempty(mainFigObj) || ~isvalid(mainFigObj)
    mainFigObj = uifigure('Tag','mainFigure');
end
winState = mainFigObj.WindowState;

% ------------------ Dialog Size ------------------
width  = 660;
height = 700;

% ------------------ Modal About Dialog ------------------
dlg = uifigure( ...
    'Name','App Information', ...
    'WindowStyle',getWindowsStyleFromSettings(), ...
    'MenuBar','none', ...
    'ToolBar','none', ...
    'NumberTitle','off', ...
    'Resize','off', ...
    'Resize','off', ...
    'Position',[100 100 width height], ...
    'CloseRequestFcn',@(src,evt)closeDialog(src,winState), ...
    'Visible','on');
theme(dlg,getSettingsValue('Style'));
movegui(dlg,'center')

% ------------------ App Logo ------------------
uiimage(dlg, ...
    'ImageSource','Icon4.png', ...
    'Position',[width-215 height-215 200 200], ...
    'ScaleMethod','fit');

% ------------------ App Title ------------------
uilabel(dlg, ...
    'Text',getSettingsValue('AppName'), ...
    'FontSize',22, ...
    'FontWeight','bold', ...
    'HorizontalAlignment','left', ...
    'Position',[20 height-45 width-250 30]);

versionString = sprintf('Version %s  %s-%s-%s', ...
    getSettingsValue('Version'), ...
    getSettingsValue('Day'), ...
    getSettingsValue('Month'), ...
    getSettingsValue('Year'));

uilabel(dlg, ...
    'Text',versionString, ...
    'FontSize',18, ...
    'Position',[20 height-80 width-250 25]);

% ------------------ Developer ------------------
uilabel(dlg,...
    'Text','Developed by:',...
    'FontSize',18,...
    'FontWeight','bold',...
    'Position',[20 height-130 300 24]);

uilabel(dlg,...
    'Text','Sebastian Friedrich, BEng',...
    'FontSize',16,...
    'Position',[70 height-160 450 22]);

% ------------------ Contributors ------------------
uilabel(dlg,...
    'Text','With the help of:',...
    'FontSize',18,...
    'FontWeight','bold',...
    'Position',[20 505 300 24]);

uilabel(dlg,...
    'Text','David Goodwin, BSc',...
    'FontSize',16,...
    'Position',[70 475 450 22]);

uilabel(dlg,...
    'Text','The Royal Veterinary College',...
    'FontSize',14,...
    'Position',[70 450 450 20]);

uilabel(dlg,...
    'Text','Justin Perkins, BVetMed MS CertES Dip ECVS MRCVS',...
    'FontSize',16,...
    'Position',[70 415 560 22]);

uilabel(dlg,...
    'Text','The Royal Veterinary College',...
    'FontSize',14,...
    'Position',[70 390 450 20]);

% ------------------ Icons ------------------
makeIcon(dlg,'IconGoogleDrive.png',[20 330 40 40])
makeIcon(dlg,'IconGithub2.png',   [20 250 40 40])
makeIcon(dlg,'IconPayPal2.png',   [20 170 40 40])

% ------------------ Links ------------------
uihyperlink(dlg,...
    'Text','sebastian.friedrich.software@gmail.com',...
    'URL','mailto:sebastian.friedrich.software@gmail.com',...
    'FontSize',16,...
    'Position',[70 330 450 22]);

uihyperlink(dlg,...
    'Text','Google Drive',...
    'URL','https://drive.google.com/drive/folders/1ZpQZU2xMfEPq2BbAiHYZUVx-WdxUNUDx?usp=share_link',...
    'FontSize',16,...
    'Position',[70 350 200 22]);

uihyperlink(dlg,...
    'Text','Github.com',...
    'URL','https://github.com/Doppelweck/Muscle_Fiber_Analyzer',...
    'FontSize',16,...
    'Position',[70 270 200 22]);

uihyperlink(dlg,...
    'Text','https://github.com/Doppelweck/Muscle_Fiber_Analyzer',...
    'URL','https://github.com/Doppelweck/Muscle_Fiber_Analyzer',...
    'FontSize',16,...
    'Position',[70 250 200 22]);

uihyperlink(dlg,...
    'Text','PayPal.com',...
    'URL','https://paypal.me/sFriedrichSoftware',...
    'FontSize',16,...
    'Position',[70 190 200 22]);

uihyperlink(dlg,...
    'Text','https://paypal.me/sFriedrichSoftware',...
    'URL','https://paypal.me/sFriedrichSoftware',...
    'FontSize',16,...
    'Position',[70 170 200 22]);

% ------------------ Disclaimer ------------------
uilabel(dlg,...
    'Text',['This App is provided free of charge for Windows and macOS. ' ...
            'Latest version is available via Google Drive. ' ...
            'Source code is hosted on GitHub. ' ...
            'Donations are voluntary and help future development.'],...
    'FontSize',14,...
    'WordWrap','on',...
    'Position',[20 40 width-40 110]);

% ------------------ Close Button ------------------
btnWidth  = 100;
btnHeight = 32;
btnX = (width - btnWidth) / 2;
btnY = 15;

btn = uibutton(dlg,...
    'Text','Close',...
    'FontSize',14,...
    'Position',[btnX btnY btnWidth btnHeight],...
    'ButtonPushedFcn',@(btn,evt)closeDialog(dlg,winState));
focus(btn);

dlg.Visible = 'on';
h = dlg;

end

% =========================================================
% Helper Functions
% =========================================================

function makeIcon(parent,imageFile,pos)
    uiimage(parent,...
        'ImageSource',imageFile,...
        'Position',pos,...
        'ScaleMethod','fit');
end

function closeDialog(fig,winState)
    delete(fig)
    mainFigObj = findobj('Tag','mainFigure');
    if ~isempty(mainFigObj) && strcmp(winState,'maximized')
        mainFigObj.WindowState = 'maximized';
    end
end